# Settings to use, possible settings are listed in the documentation (section "Customizing the extraction").
setting:
  binWidth: 15
  label: 1
  interpolator: 'sitkBSpline' # This is an enumerated value, here None is not allowed
  # resampledPixelSpacing: [0.625, 0.625, 2.4] # This disables resampling, as it is interpreted as None, to enable it, specify spacing in x, y, z as [x, y , z]
  weightingNorm: # If no value is specified, it is interpreted as None
  geometryTolerance: 0.0001
  normalize: False
 
# Image types to use: "Original" for unfiltered image, for possible filters, see documentation.
imageType:
  Original: {}
  # Square: {}
  # SquareRoot: {}
  # Logarithm: {}
  # Exponential: {}
  LoG:
  #   # If the in-plane spacing is large (> 2mm), consider removing sigma value 1.
    sigma: [2.0, 3.0, 4.0, 5.0]
  Wavelet:
    wavelet: 'db5'
    binWidth: 10
  Gradient: {}
# Featureclasses, from which features must be calculated. If a featureclass is not mentioned, no features are calculated
# for that class. Otherwise, the specified features are calculated, or, if none are specified, all are calculated.
featureClass:
  shape:  # disable redundant Compactness 1 and Compactness 2 features by specifying all other shape features
  firstorder: 
  glcm:  
  glrlm: # for lists none values are allowed, in this case, all features are enabled
  glszm:
  ngtdm:
  gldm:
 
 